OneSourceAdmin/Controllers/SLASettingController.cs
using OneSourceAdminCore.Model;
using OneSourceAdminCore.Presenter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OneSourceAdminCore.Entity;
using System.Configuration;

namespace OneSourceAdmin.Controllers
{
    /// <summary>
    /// Date created : Sep 27 2016
    /// Created by : Muhammad Wasim (BSCE,MS-CSIT)
    /// This Controller Class is responsible for providing Site Budget detail"
    /// </summary>
    public class SLASettingController : BaseController
    {
        /// <summary>
        /// This Action is responsible for returning Index View of SLA setting
        /// </summary>
        /// <param name="customerId"></param>
        /// <returns></returns>

        public ActionResult Index(string customerId = null)
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    CustomerPresenter cp = new CustomerPresenter();
                    LSASettingPresenter relp = new LSASettingPresenter();
                    SLASettingModel model = relp.GetLSASettingModel();
                    model.CustomerId = customerId ?? "";
                    ViewBag.Message = TempData["Message"];
                    @ViewBag.AddEditAccess = isAddEditAllow("SlaSettings");
                    return View(model);
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        /// <summary>
        /// This Action is responsible for Adding new SLA
        /// </summary>
        /// <param name="SLAName"></param>
        /// <returns></returns>
        public ActionResult AddSLA(string SLAName)
        {
            LSASettingPresenter relp = new LSASettingPresenter();
            int count = relp.AddSLA(SLAName, Convert.ToInt32(Session["UserID"]));
            TempData["Message"] = count > 0 ? "SLA has been added" : "SLA already exists";
            return RedirectToAction("Index");
        }
        /// <summary>
        /// This action is reponsible for returning the SLA information of customer
        /// </summary>
        /// <param name="customerId"></param>
        /// <returns></returns>
        public JsonResult GetSLAinfo(int customerId)
        {
            LSASettingPresenter relp = new LSASettingPresenter();
            SLASettingModel data = relp.GetSLAinfo(customerId);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This action is responsible for Adding SLA to Customer mapping
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult AddSLAToCustomer(SLAModel model)
        {
            LSASettingPresenter relp = new LSASettingPresenter();
            int count = relp.AddSLACustomerWise(model, Convert.ToInt32(Session["UserID"]));
            if (count > 0) TempData["Message"] = "SLA has been set";
            count = relp.SetCustomerView(model.Viewable, model.CustomerId);
            if (count > 0) TempData["Message"] = "SLA has been set";
            return RedirectToAction("Index", new { customerId = model.CustomerId });
        }
        public ActionResult DeleteCustomerSLA(string hCustomerId, string SLAIds)
        {

            if (!string.IsNullOrEmpty(hCustomerId) && !string.IsNullOrEmpty(SLAIds))
            {
                LSASettingPresenter relp = new LSASettingPresenter();
                int count = relp.DeleteCustomerSLA(hCustomerId, SLAIds);
                if (count > 0) TempData["Message"] = "Customer SLA record has been deleted";
                return RedirectToAction("Index", new { customerId = hCustomerId });

            }
            else
            {
                TempData["Message"] = "Please provide correct info!";
                return RedirectToAction("Index");
            }
        }



        #region OrderQuoteSLA

        public ActionResult OrderQuoteSLA()
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    ViewBag.Message = TempData["Message"];
                    @ViewBag.AddEditAccess = isAddEditAllow("LocaleOrderQuoteSla");
                    LSASettingPresenter relp = new LSASettingPresenter();
                    return View(relp.GetOrderQuoteSLAs());
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }
        public ActionResult UpdateOrderQuoteSLA(List<sp_getSLAs_AdminR_Result> sp_getSLAs_AdminR_Result)
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    LSASettingPresenter lsa = new LSASettingPresenter();
                    int count = lsa.UpdateOrderQuoteSLA(sp_getSLAs_AdminR_Result, Convert.ToInt32(Session["UserID"]));
                    if (count > 0) TempData["Message"] = "Record has been updated successfully";
                    else TempData["Message"] = "Error occured";
                    return RedirectToAction("OrderQuoteSLA");
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }
        #endregion

        #region Other OEM Specific SLA's
        //[Route("locale-settings/oem-specific-sla")]
        public ActionResult OEMSpecificSLAs()
        {
            try
            {
                LSASettingPresenter relp = new LSASettingPresenter();
                OEMSpecificSLAsModel model = relp.GetOEMSpecificSLAModel();
                @ViewBag.AddEditAccess = isAddEditAllow("OEMSpecificSLAs");
                return View(model);
            }
            catch (Exception ex)
            {
                var routeData = this.ControllerContext.RouteData;
                LogException(ex.Message, routeData);
                if (ex.InnerException != null)
                {
                    LogException(ex.InnerException.ToString(), routeData);
                }
                return View("~/Views/Shared/ErrorPage.cshtml");
            }

        }
        public JsonResult GetOEMSpecificSLAs(int countryId, int manufacturerId)
        {
            LSASettingPresenter obj = new LSASettingPresenter();
            var data = obj.GetSLAByOEM(countryId, manufacturerId);
            if (data == null)
                return Json("0", JsonRequestBehavior.AllowGet);
            else
                return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpdateOEMSpecificSLAs(OEMSpecificSLAsModel model)
        {
            if (model != null)
            {
                LSASettingPresenter obj = new LSASettingPresenter();
                int count = obj.UpdateOEMSpecificSLAs(model, adminSetting.UserID);
                return Json(count, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("0", JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region local taxes
        //[Route("locale-settings/local-taxes")]
        public ActionResult LocalTaxes()
        {
            try
            {
                CountryPresenter cp = new CountryPresenter();
                var countries = cp.GetCountries();
                countries.Insert(0, new GenericList { Key = 0, Value = "(None)" });
                ViewBag.Countries = countries;
                @ViewBag.AddEditAccess = isAddEditAllow("LocalTaxes");
                return View();
            }
            catch (Exception ex)
            {
                var routeData = this.ControllerContext.RouteData;
                LogException(ex.Message, routeData);
                if (ex.InnerException != null)
                {
                    LogException(ex.InnerException.ToString(), routeData);
                }
                return View("~/Views/Shared/ErrorPage.cshtml");
            }

        }

        public JsonResult GetCountryTax(int countryId)
        {
            LSASettingPresenter obj = new LSASettingPresenter();
            var data = obj.GetCountryTax(countryId);
            if (data == null)
                return Json("0", JsonRequestBehavior.AllowGet);
            else
                return Json(data, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateCountryTax(int countryId, decimal? localtax)
        {
            if (countryId > 0)
            {
                LSASettingPresenter obj = new LSASettingPresenter();

OneSourceAdmin/Views/SLASetting/Index.cshtml
@{
    ViewBag.Title = "SLA Settings";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<script src="~/Content/assets/global/plugins/angularjs/angular.min.js"></script>

<script>
    var myApp = angular.module("myModule", []);
    myApp.controller("myController", function ($scope, $http) {
        $scope.getSLAinfo = function (id) {
            
            StartLoader();
            $scope.$apply(function () {
                $scope.priorities = null;
                $scope.genericpriorities = null;
            });
            if (id !== "") {
              
                $http.get('/SLASetting/GetSLAinfo'+'?' + new Date().toString(), { params: { customerid: id } }).success(function (response) {
                  
                    $scope.selectedSLA = response.LstSelectedSLA;
                    $scope.unselectedSLA = response.LstUnselectedSLA;
                    $('input[name="Viewable"]').val(response.Viewable);
                    $('#isViewable').prop('checked', response.Viewable);

                    if (response.LstSelectedSLA.length > 0) {
                        $('.SLAGrid').show();
                    }
                    else {
                        $('.SLAGrid').hide();
                    }
                });
            }
            EndLoader();

        };

        $scope.showLists = function () {
            if ($('#CustomerID').val() == "") return false;
            else return true;
        };


    });

</script>
<div class="clearfix"></div>
<div class="row bread-Crumb-Top" style="background-color: #216481; padding: -10px; margin-left: -20px;
                                       margin-right: -19px;">
    <div class="col-md-3" style="padding: 10px; color: #FFF;">
        <b> Settings > SLA Settings </b>
    </div>
    <div class="col-md-3" style="padding: 10px;"></div>
    <div class="col-md-3" style="padding: 10px;"></div>
</div>
<div style="text-align: center; color: blue; font-weight: 600; margin-top: 10px; margin-bottom: -20px;">
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-info fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <span>@ViewBag.Message</span>
        </div>
    }
</div>
@*<div class="row" style="background-color: #3a9ada; padding: -10px; margin-left: -20px; margin-top: 30px; margin-right: -19px;">
        <div class="col-md-12">
            <h1 style="color: #fff;">Settings > Generic SLA Settings</h1>
        </div>
        <div class="col-md-4" style="font-size: 32px; color: #FFF; padding: 18px; padding-top: 2px;">
        </div>
        <div class="col-md-4"></div>
    </div>*@

<div ng-app="myModule" ng-controller="myController" id="myController">
    @if (ViewBag.AddEditAccess == true)
    {
    using (Html.BeginForm("AddSLA", "SLASetting", FormMethod.Post, new { @id = "SLASettingForm" }))
    {
        <div class="row" style="margin-top: 60px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-3"><span style="color:red">* </span>Add New SLA</label>
                    <div class="col-md-6">
                        <input type="text" maxlength="100" class="form-control" name="SLAName" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row" style="margin-top: 15px;">

            <div class="col-md-4"></div>
            <div class="col-md-7" style="padding-left: 23px;">
                <button type="submit" class="btn btn-default btnSubmit" style="float: left; margin-left: 20px; margin: 0px;" id="per">Add</button>
                <button type="button" class="btn btn-default btnReset" style="float: left; margin-left: 5px;" id="per">Reset</button>
            </div>
            <br>
            <br>
        </div>
    }
    <div class="row" style="margin-top: 0px;">
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label col-md-12"><h4>Set SLA For Customer</h4> </label>

            </div>
        </div>
    </div>
    }
    @using (Html.BeginForm("AddSLAToCustomer", "SLASetting", FormMethod.Post, new { @id = "SLAToCustomerForm" }))
    {
        <div class="row" style="margin-top: 60px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-3" style="padding-left: 20px;"><span style="color:red">* </span>Customer</label>
                    <div class="col-md-6">
                        <input type="hidden" name="CustomerId" id="CustomerId">
                        <select class="form-control " id="CustomerID" valuefor="CustomerName" idfor="CustomerId" tabindex="-1">
                            <option value="">--Select--</option>
                            @foreach (var item in Model.Customers)
                            {
                                <option value="@item.CustomerId" companyid="@item.ParentCompanyId">@item.CustomerName</option>
                            }
                        </select>


                    </div>
                </div>
            </div>
        </div>

        if (ViewBag.AddEditAccess == true)
        {
        <div class="row" style="margin-top: 15px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-3" ><span>&nbsp;&nbsp;&nbsp; </span>Display SLA</label>
                    <div class="col-md-6">
                        <input type="hidden" name="Viewable" value="false">
                        <input type="checkbox" id="isViewable">
                    </div>
                </div>
            </div>
        </div>
        }
        <div class="row" style="margin-top: 40px;" ng-show="showLists()">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">

                    <div class="col-md-6">                     
                            <select class="form-control " id="unselectedSLA" name="unselectedSLA" tabindex="-1" multiple style="height: 150px;">
                                <option ng-repeat="row in unselectedSLA" value="{{row.GenericRequestSLAId}}">{{row.SLAName}}</option>                           
                            </select>                      
                    </div>
                    <div class="col-md-6">
                        <select class="form-control " id="selectedSLA" name="selectedSLA" tabindex="-1" multiple disabled style="height: 150px;">
                            <option ng-repeat="row in selectedSLA" value="{{row.Key}}">{{row.Value}}</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>


        if (ViewBag.AddEditAccess == true)
        {
        <div class="row" style="margin-top: 15px;">

            <div class="col-md-4"></div>
            <div class="col-md-7" style="padding-left: 23px;">
                <button type="submit" class="btn btn-default" style="float: left; margin-left: 20px;margin: 0px;" id="per" ng-disabled="isStandard">Update</button>
                <button type="button" class="btn btn-default btnReset1" style="float: left; margin-left: 5px;" id="per">Reset</button>
            </div>
            <br>
            <br>
        </div>
        }

    }
@using (Html.BeginForm("DeleteCustomerSLA", "SLASetting", FormMethod.Post, new { @id = "SLACustomerDeleteForm" }))
{
    <div ng-show="showLists()" class="SLAGrid">
        <div class="row">
            <div class="col-md-2"></div>

            <div class="col-md-8" style="margin-top: 15px;padding-right:0px">
                <table class="table" style="margin-bottom: 0px;">
                    <thead style="color: #fff;background-color: #399bd3;">
                        <tr>
                            @if (ViewBag.AddEditAccess == true)
                            {
                            <th style="width: 22%;font-size: 10px;">
                                <input type="checkbox" class="pchkSLA"><br />
                                Check/Uncheck All
                            </th>
                            }
                            <th style="width: 85%;font-size: 17px;">SLA</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-12"></div>
            <div class="col-md-2"></div>
            <div class="col-md-8" style="max-height:350px;overflow-x:hidden">
                <table class="table tblProd">

                    <tbody>
                        <tr ng-repeat="row in selectedSLA">
                            @if (ViewBag.AddEditAccess == true)
                            {
                            <td style="width:22%">
                                <input type="checkbox" class="chkSLA">
                                <input type="hidden" value="{{row.Key}}" />
                            </td>
                            }
                            <td>

                                <span>{{row.Value}}</span>
                            </td>
                        </tr>

                    </tbody>
                </table>
                <input type="hidden" name="SLAIds" />
                <input type="hidden" name="hCustomerId" id="hCustomerId">
            </div>

        </div>
        @if (ViewBag.AddEditAccess == true)
        {
        <div class="row" style="margin-top: 15px;">
            <div class="col-md-4"></div>
            <div class="col-md-7" style="padding-left: 23px;">
                <button type="submit" class="btn btn-default" style="float: left; margin-left: 5px;" id="per">Delete</button>
            </div>
            <br>
            <br>
        </div>
        }
    </div>
}
</div>
<script>
    function setcheckboxes() {
        var count = 0;
        var SLA = "";
        $('.chkSLA').each(function () {
            if ($(this).is(":checked")) {
                SLA += $(this).siblings().val() + ",";
                count++;
            }
        });
        if (SLA.length > 0) {
            SLA = SLA.substring(0, SLA.length - 1);
            $('input[name="SLAIds"]').val(SLA);
        }
        else {
            $('input[name="SLAIds"]').val("");
        }

        

    }
    $('body').on('click', 'input.chkSLA', function () {
        setcheckboxes();
    });
    $('body').on('click', 'input.pchkSLA', function () {
        if ($(this).is(":checked")) {
            $('.chkSLA').prop("checked", true);
            setcheckboxes();
        }
        else {
            $('input[name="SLAIds"]').val("");
            $('.chkSLA').prop("checked", false);

        }
    });
    $('#isViewable').click(function () {
        if ($(this).prop('checked')) {
            $('input[name="Viewable"]').val('true');
        }
        else {
            $('input[name="Viewable"]').val('false');
        }
    });


    $(window).ready(function () {


        var customerId = "@Model.CustomerId";
        if (customerId.length > 0) {
            //angular.element(document.getElementById('myController')).scope().getPriorities(0, companyId);
            $('#CustomerID').val(customerId).change();
        }
       
    });
    $("#SLASettingForm").submit(function () {
        if ($('input[name="SLAName"]').val() == "") {
            alert("Please provide SLA");
            return false;
        }
    });

    $('#SLAToCustomerForm').submit(function () {
        //var unselectedSLA = '';
        //$('#unselectedSLA option:selected').each(function (e, t) {
        //    unselectedSLA += $(t).text().trim() + ",";
        //});
        //unselectedSLA = unselectedSLA.substring(0, unselectedSLA.length - 1);
        //$('#unselectedSLA').val(unselectedSLA);

        //if (unselectedSLA == '') {
        //    alert("Please select atleast SLA");
        //    return false;
        //}
        if ($('#CustomerID').val() == "") {
            alert("Please select customer");
            return false;

        }
        //if($('#unselectedSLA option:selected').val() == undefined)
        //{
        //    alert("Please select atleast SLA");
        //        return false;
        //}
    });


    $('#CustomerID').change(function () {

        angular.element(document.getElementById('myController')).scope().getSLAinfo($(this).val());
        $('input[name="SLAIds"]').val("");
        
       
    });

    $('.btnReset').click(function () {
        $('input[name="SLAName"]').val("");
    });
    $('.btnReset1').click(function () {

        $('#CustomerID').val('').change();
        //  angular.element(document.getElementById('myController')).scope().updateStandard();
    });
    $(function () {
        setTimeout(function () {
            $('.alert-info').slideUp();
        }, 2000);

    });
    $('#SLACustomerDeleteForm').submit(function () {
        if ($('#CustomerID').val() == "" || $('input[name="SLAIds"]').val() == "") {
            alert("Please select customer and SLA to delete");
            return false;
        }
        $('#hCustomerId').val($('#CustomerID').val());
    });
    $(document).ready(function () {
        $(".page-sidebar-menu").find(".settings").addClass("open");
        $(".page-sidebar-menu .settings").find(".sub-menu").css("display", "block");
        $(".page-sidebar-menu .settings").find(".slasetting").addClass("active");
    });
</script>

OneSourceAdmin/Views/SLASetting/OrderQuoteSLA.cshtml
@model List<OneSourceAdminCore.Entity.sp_getSLAs_AdminR_Result>
@{
    ViewBag.Title = "Order & Quote SLAs";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div class="clearfix"></div>
<div class="row bread-Crumb-Top" style="background-color: #216481; padding: -10px; margin-left: -20px;
                                       margin-right: -19px;">
    <div class="col-md-3" style="padding: 10px; color: #FFF;">
        <b> Other > Order & Quote SLAs </b>
    </div>
    <div class="col-md-3" style="padding: 10px;"></div>
    <div class="col-md-3" style="padding: 10px;"></div>
</div>

<div style="text-align: center; color: blue; font-weight: 600; margin-top: 10px; margin-bottom: -20px;">
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-info fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <span>@ViewBag.Message</span>
        </div>
    }
</div>
<div class="clearfix"></div>
<div class="col-md-12 catalog-add-new" style="margin-top: 40px;">
    <button type="submit" class="btn btn-default btnSubmit pull-right" id="pmfc-back" style="margin-right: 10px;">Back</button>
</div>
@using (Html.BeginForm("UpdateOrderQuoteSLA", "SLASetting", FormMethod.Post, new { @id = "OrderQuoteSLAForm" }))
{
    <div class="row" style="margin-top: 40px;">
        <div class="col-md-2"></div>
        <div class="col-md-8" style="margin-top: 15px;padding-right:0px">
            <table class="table" style="margin-bottom: 0px !important;">
                <thead style="color: #fff;background-color: #399bd3;">
                    <tr>
                        <th style="width: 40%;font-size: 14px;">Country</th>
                        <th style="width: 20%;font-size: 14px;">Order Delivery SLA (Business Days)</th>
                        <th style="width: 20%;font-size: 14px;">Order Acceptance SLA (Business Days)</th>
                        <th style="width: 20%;font-size: 14px;">Quote Response SLA (Business Days)</th>
                    </tr>
                </thead>
            </table>

        </div>
        <div class="col-md-2"></div>
        <div class="col-md-12"></div>
        <div class="col-md-2"></div>

        <div class="col-md-8" style="height:500px !important;overflow:scroll;overflow-x:hidden">
            <table class="table">
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        if (ViewBag.AddEditAccess == true)
                        {
                            <tr>
                                <td style="width: 40%;" class="countryName">
                                    @Model[i].CountryName
                                    <input type="hidden" name="sp_getSLAs_AdminR_Result[@i].CountryID" value="@Model[i].CountryID">
                                </td>

                                <td style="width: 20%;">
                                    <input type="text" class="form-control allownumericwithoutdecimal" name="sp_getSLAs_AdminR_Result[@i].Days" value="@Model[i].Days" maxlength="8">
                                </td>
                                <td style="width: 20%;">
                                    <input type="text" class="form-control allownumericwithoutdecimal" name="sp_getSLAs_AdminR_Result[@i].AcceptanceDays" value="@Model[i].AcceptanceDays" maxlength="8">
                                </td>
                                <td style="width: 20%;">
                                    <input type="text" class="form-control allownumericwithoutdecimal" name="sp_getSLAs_AdminR_Result[@i].QuoteResponseDays" value="@Model[i].QuoteResponseDays" maxlength="8">
                                </td>
                            </tr>


                        }
                        else
                        {
                            <tr>
                                <td style="width: 40%;text-align: center;" class="countryName">
                                    @Model[i].CountryName
                                </td>

                                <td style="width: 20%;text-align: center;">
                                   @Model[i].Days
                                </td>
                                <td style="width: 20%;text-align: center;">
                                   @Model[i].AcceptanceDays
                                </td>
                                <td style="width: 20%;text-align: center;">
                                    @Model[i].QuoteResponseDays
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <div class="col-md-2"></div>
            <div class="col-md-8">

            </div>
        </div>
        @if (ViewBag.AddEditAccess == true)
        {
            <div class="col-md-12" style="margin-top: 10px;">
                <div class="col-md-11"></div><div class="col-md-1">
                    <button class="btn btn-primary Btnupdate" type="submit">Update</button>
                </div>
            </div>
        }
    </div>

}
<script>
    $(document).ready(function () {
        //$('body').css("overflow", "hidden");
        StartLoader();

        setTimeout(function () {
            $('.alert-info').slideUp();
        }, 2000);

        $(".page-sidebar-menu").find(".locale").addClass("open");
        $(".page-sidebar-menu .locale").find(".sub-menu").css("display", "block");
        $(".page-sidebar-menu .locale").find(".orderquotesla").addClass("active");
    });
    $('#OrderQuoteSLAForm').submit(function () {
        StartLoader();
    });
    $(window).ready(function () {
        EndLoader();

    });
    $('#pmfc-back').click(function () {
        window.location.href = "/admin-dashboard";
    });
</script>