OneSourceAdmin/Controllers/OstCustomerCategoryController.cs
using OneSourceAdmin.ViewModels;
using OneSourceAdminCore.Presenter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OneSourceAdmin.Controllers
{
    /// <summary>
    /// Date created : Oct 20 2016
    /// Created by : Muhammad Wasim (BSCE,MS-CSIT)
    /// This Controller Class is responsible for providing Customer's category detail"
    /// </summary>
    public class OstCustomerCategoryController : BaseController
    {
        CustomerCategoriesPresenter ccp;
        OneStreetPropertyViewModel model;
        public OstCustomerCategoryController() //Constructor
        {
            ccp = new CustomerCategoriesPresenter();
            model = new OneStreetPropertyViewModel();
        }

        // GET: /OstCustomerProduct/
        /// <summary>
        /// This Action is responsible for returning Index View of Customer's Category
        /// </summary>
        /// <returns></returns>              
        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    CustomerPresenter cp = new CustomerPresenter();
                    ViewBag.Message = TempData["Message"];
                    @ViewBag.AddEditAccess = isAddEditAllow("OsCategorySetup");
                    return View(cp.GetCustomers());
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        /// <summary>
        /// This Action is responsible for returning json result of Customer's Manufacturer
        /// </summary>
        /// <param name="customerId"></param>
        /// <returns></returns>
        ///
        public JsonResult GetManufacturers(int customerId)
        {
            return Json(ccp.GetManufacturers(customerId), JsonRequestBehavior.AllowGet);
        }


        [Route("OstCustomerCategory/GetManufacturersCatalogSetup/{customerId}")]
        public JsonResult GetManufacturersCatalogSetup(int customerId)
        {
            model.ManufacturerName = ccp.GetManufacturersCatalogSetup(customerId);
            return Json(model.ManufacturerName, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This Action is responsible for returning json result of categories by customer and Manufacturer
        /// </summary>
        /// <param name="manufacturerId"></param>
        /// <param name="customerId"></param>
        /// <returns></returns>
        public JsonResult GetCategories(int manufacturerId, int customerId)
        {
            return Json(ccp.GetCategories(manufacturerId, customerId), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This Action is responsible for update the customer's categories
        /// </summary>
        /// <param name="customerId"></param>
        /// <param name="manufacturerId"></param>
        /// <param name="categoriesIds"></param>
        /// <returns></returns>
        public ActionResult UpdateCustomerCategorySetting(int customerId, int manufacturerId, string categoriesIds)
        {
            if (customerId > 0)
            {
                int a = ccp.UpdateCustomerCategorySetting(customerId, manufacturerId, categoriesIds, Convert.ToInt32(Session["UserID"]));
                TempData["Message"] = a > 0 ? "Record successfully updated" : "No record was updated";
                return RedirectToAction("Index", new { @customerId = customerId, @manufacturerId = manufacturerId });
            }
            TempData["Message"] = "Please provide correct data";
            return RedirectToAction("Index", new { @customerId = customerId, @manufacturerId = manufacturerId });
        }
    }
}

OneSourceAdmin/Views/OstCustomerCategory/Index.cshtml
@model List<OneSourceAdminCore.Model.GenericList>
@{
    ViewBag.Title = "Category Setup";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<script src="~/Content/assets/global/plugins/angularjs/angular.min.js"></script>
<script>
    var myApp = angular.module("myModule", []);
    myApp.controller("myController", function ($scope, $http) {

        $scope.getManufacturers = function (id) {

            $scope.$apply(function () {
                $scope.categories = null;
                $scope.manufacturers = null;
            });
            $('input[name="categoriesIds"]').val("");
            $('#ManufacturerID').val("");

            if (id != "") {
                StartLoader();
                $http.get('/OstCustomerCategory/GetManufacturers' + '?' + new Date().toString(), { params: { customerId: id } }).success(function (response) {
                    
                    $scope.manufacturers = response;
                    $scope.GetCategories(0, id);
                    EndLoader();
                });
            }



        };
        $scope.GetCategories = function (id, cId) {

            $scope.$apply(function () {
                $scope.categories = null;
                $('input[name="categoriesIds"]').val("");
            });

            ///if (id != "0") {
                StartLoader();
                $http.get('/OstCustomerCategory/GetCategories' + '?' + new Date().toString(), { params: { manufacturerId: id, customerId: cId } }).success(function (response) {
                    $scope.categories = response;

                    $('.chkCat').prop("checked", false);
                    var selectedCategories = "";
                    $.each(response, function (i, v) {
                        if (v.status > 0) {
                            $('.table :input[value="' + v.status + '"]').prev().prop("checked", "true");
                            selectedCategories += v.status + ",";
                        }
                    });




                    selectedCategories.length == 0 ? $('input[name="categoriesIds"]').val("") : $('input[name="categoriesIds"]').val(selectedCategories.substring(0, selectedCategories.length - 1));


                    setTimeout(function () {
                        setcheckboxes();
                        //for rearrange seleted rows
                        var selectedCol = [];
                        $('.chkCat').each(function (e, t) {
                            if ($(t).prop("checked")) {
                                selectedCol.push($(t).parent());
                            }

                        });
                        if (selectedCol.length > 0) {
                            var options = [];
                            $.each(selectedCol, function (e, r) {
                                var row = $(r).parent();
                                if ($('.tblCat tr').length > 1) {
                                    $('.tblCat').find(row).remove();
                                }
                                options.push($(row));
                            });
                            $('.tblCat tr:first').before(options);
                        }
                        setTimeout(function () {
                            if ($('.chkCat').length == selectedCol.length) {
                                $('.pchkCat').prop("checked", true);
                            }
                            else {
                                $('.pchkCat').prop("checked", false);
                            }
                        }, 100);
                        //
                        EndLoader();
                    }, 500);

                });
            //}




        };
        $scope.reset = function () {
            $scope.categories = null;
            $scope.manufacturers = null;
            $('#CustomerID').val("");
            $('#ManufacturerID').val("");
            $('input[name="categoriesIds"]').val("");
            $('.chkCat').prop("checked", false);
            $('.pchkCat').prop("checked", false);
            setcheckboxes();
        };
    });

</script>
<div ng-app="myModule" ng-controller="myController" id="myController">
    <div class="clearfix"></div>
    <div class="row bread-Crumb-Top" style="background-color:#216481; padding: -10px; margin-left: -20px;
        margin-right: -19px;">
        <div class="col-md-3" style="padding:10px; color:#FFF;"><b> OneStreet > Category Setup</b></div>
        <div class="col-md-3" style="padding:10px;"></div>
        <div class="col-md-3" style="padding:10px;"></div>
    </div>
    <div style=" text-align: center; color: blue; font-weight: 600; margin-top: 10px; margin-bottom: -20px;">
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-info fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <span>@ViewBag.Message</span>
            </div>
        }
    </div>

    @using (Html.BeginForm("UpdateCustomerCategorySetting", "OstCustomerCategory", FormMethod.Post, new { @id = "CCForm" }))
    {
        <div class="row" style="margin-top: 60px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-3" style="padding-left: 20px;"><span style="color:red">* </span>Customer </label>
                    <div class="col-md-6">
                        <input type="hidden" name="CustomerName" id="CustomerName">
                        <input type="hidden" name="CustomerAlertId" id="CustomerAlertId">
                        @Html.DropDownList("customerId", new SelectList(Model,
"Key", "Value"),
new { @id = "CustomerID", @valueFor = "CustomerName", @class = "", @tabindex = "-1" })
                    </div>
                </div>
            </div>
        </div>

        <div class="row" style="margin-top: 15px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-3" style="padding-left: 20px;"><span style="color:red">* </span>Manufacturer</label>
                    <div class="col-md-6">
                        <select class="" id="ManufacturerID" name="manufacturerId" tabindex="-1">
                            @*<option value="0">--All--</option>*@
                            <option ng-repeat="row in manufacturers" value="{{row.ManufacturerID}}">{{row.ManufacturerName}}</option>

                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" ng-show="categories.length>0">
            <div class="col-md-2"></div>

            <div class="col-md-8" style="margin-top: 15px;padding-right:0px">
                <b style="float:right">
                    <span id="totalCount">Selected Category(ies) : 0</span>
                </b>
                <table class="table" style="margin-bottom: 0px;">
                    <thead style="color: #fff;background-color: #399bd3;">
                        <tr>
                            @if (ViewBag.AddEditAccess == true)
                            {
                            <th style="width: 22%;font-size: 10px;">
                                <input type="checkbox" class="pchkCat"><br />
                                Check/Uncheck All
                            </th>
                            }
                            <th style="width: 80%;font-size: 17px;">Categories <input type="text" placeholder="Search categories" class="form-control searchCat searchGridResult" /></th>
                        </tr>
                    </thead>
                </table>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-12"></div>
            <div class="col-md-2"></div>


            <div class="col-md-8" style="max-height:350px;overflow-x:hidden">
                <table class="table tblCat">
                    <tbody>
                        <tr ng-repeat="a in categories">
                           
                            <td class="categoryName" style="width: 22%">
                                <input type="checkbox" class="chkCat" ng-checked="{{a.status>0==true?true:false}}" @(ViewBag.AddEditAccess == true?"": "disabled")>
                                <input type="hidden" value="{{a.TreeClassClassificationID}}" />
                            </td>

                            <td>

                                <span>{{a.TreeClassClassificationName}}</span>
                            </td>
                        </tr>

                    </tbody>
                </table>
                <input type="hidden" name="categoriesIds" />

            </div>

        </div>

        if (ViewBag.AddEditAccess == true)
        {
        <div class="row" style="margin-top: 15px;">

            <div class="col-md-4"></div>
            <div class="col-md-7" style="padding-left: 23px;">
                <button type="submit" class="btn btn-default btnSubmit" style="float: left; margin-left: 20px; margin: 0px;" id="per">Submit</button>
                <button type="button" class="btn btn-default btnReset" style="float: left; margin-left: 5px;" id="per" ng-click="reset()">Reset</button>
            </div>
            <br>
            <br>
        </div>
        }

    }

</div>
<script>

    $('#CustomerID').change(function () {

        angular.element(document.getElementById('myController')).scope().getManufacturers($(this).val());
        
});
    $('#ManufacturerID').change(function () {
    angular.element(document.getElementById('myController')).scope().GetCategories($(this).val(), $('#CustomerID').val());
});

    $(function () {

    setTimeout(function () {
            $('.alert-info').slideUp();
    }, 2000);

    var url = window.location.href.split('?');
    if (url.length > 1) {
        var customerId = url[1].split('&')[0].split('=')[1];
        var manufacturerId = url[1].split('&')[1].split('=')[1];

        angular.element(document.getElementById('myController')).scope().getManufacturers(customerId);

        angular.element(document.getElementById('myController')).scope().GetCategories(manufacturerId, customerId);
        StartLoader();
        setTimeout(function () {
                $('#ManufacturerID').val(parseInt(manufacturerId));
            EndLoader();
        }, 1000);

    }
});
    $(window).ready(function () {
    EndLoader();
});


function setcheckboxes() {
    var count = 0;
    var categories = "";
        $('.chkCat').each(function () {
        if ($(this).is(":checked")) {
            categories += $(this).siblings().val() + ",";
            count++;
        }
    });
    if (categories.length > 0) {
        categories = categories.substring(0, categories.length - 1);
            $('input[name="categoriesIds"]').val(categories);
    }
    else
    {
            $('input[name="categoriesIds"]').val("");
    }
        $('#totalCount').text("Selected Category(ies) : " + count);

}
    $('body').on('click', 'input.chkCat', function () {
    setcheckboxes();
});
    $('body').on('click', 'input.pchkCat', function () {
    if ($(this).is(":checked")) {
            $('.chkCat').prop("checked", true);
        setcheckboxes();
    }
        else {
            $('input[name="categoriesIds"]').val("");
            $('.chkCat').prop("checked", false);
            $('#totalCount').text("Selected Category(ies) : 0");
    }
});




    $('#CCForm').submit(function () {

    if ($('#CustomerID').val() == "" || $('#ManufacturerID').val() == "") {
        alert("Customer, manufacturer and categories are required");
        return false;
    }
    StartLoader();
    setcheckboxes();
});
    $(document).ready(function () {
        $(".page-sidebar-menu").find(".onestreet").addClass("open");
        $(".page-sidebar-menu .onestreet").find(".sub-menu").css("display", "block");
        $(".page-sidebar-menu .onestreet").find(".categorysetup").addClass("active");

        $("#CustomerID").prepend("<option value='0'>--Select--</option>");
        $("#CustomerID").select2().val("0").trigger("change");
       
        $("#ManufacturerID").prepend("<option value='0'>--All--</option>");
        $("#ManufacturerID").select2().val("0").trigger("change");
});
</script>