OneSourceAdmin/Controllers/PriceDeskReportsController.cs
using Newtonsoft.Json;
using OneSourceAdminCore.Helper;
using OneSourceAdminCore.Model;
using OneSourceAdminCore.Presenter;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.Entity.Core.EntityClient;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace OneSourceAdmin.Controllers
{
    public class PriceDeskReportsController : BaseController
    {
        CurrencyPresenter currencyService;
        CustomerPresenter customerService;
        PriceDeskReportsPresenter pricedeskReportsPresenter;
        CountryPresenter countryService;
        AdminMenuService adminMenuService;
        SFAsPresenter _sfa;

        #region Constructor
        public PriceDeskReportsController()
        {
            pricedeskReportsPresenter = new PriceDeskReportsPresenter();
            customerService = new CustomerPresenter();
            countryService = new CountryPresenter();
            adminMenuService = new AdminMenuService();
            currencyService = new CurrencyPresenter();
            _sfa = new SFAsPresenter();
        }

        #endregion

        #region Utilities
        public static string GetEnumDescription<TEnum>(TEnum value)
        {
            FieldInfo fi = value.GetType().GetField(value.ToString());

            DescriptionAttribute[] attributes = (DescriptionAttribute[])fi.GetCustomAttributes(typeof(DescriptionAttribute), false);

            if ((attributes != null) && (attributes.Length > 0))
                return attributes[0].Description;
            else
                return value.ToString();
        }


        #endregion

        #region Methods

        public PriceDeskReportModel GetPriceDeskModel(int id)
        {
            PriceDeskReportModel model = new PriceDeskReportModel();
            var route = adminMenuService.GetMenuById(id);
            string name = route.MenuName.ToLower().Trim().Replace(" ", "");
            var parentRoute = adminMenuService.GetMenuById(Convert.ToInt32(route.ParentMenuId));
            model.routeId = route.MenuId;
            model.routeName = name;
            model.reportName = route.MenuName;
            model.parentRouteId = parentRoute.MenuId;
            model.parentName = parentRoute.MenuName;
            model.parentRoute = parentRoute.MenuLink;
            model.excelAction = "ExportPriceDeskReportToExcel";
            model.pdfAction = "ExportProcurementReportToPdf";
            model.Suppliers = _sfa.GetSFAs().OrderBy(x => x.SFAName).Select(s => new Suppliers { SupplierName = s.SFAName ?? "-", SupplierId = s.SFAID }).ToList();
            model.Suppliers.Insert(0, new Suppliers { SupplierId = 0, SupplierName = "--Select--" });

            return model;
        }
        public ActionResult PriceDeskReport(int id, bool? fromback = false)
        {
            try
            {

                if (id > 0)
                {
                    PriceDeskReportModel model = GetPriceDeskModel(id);// new PriceDeskReportModel();

                    //var route = adminMenuService.GetMenuById(id);
                    //string name = route.MenuName.ToLower().Trim().Replace(" ", "");
                    //var parentRoute = adminMenuService.GetMenuById(Convert.ToInt32(route.ParentMenuId));

                    //Session["routeId"] = route.MenuId;
                    //Session["routeName"] = name;
                    //Session["reportName"] = route.MenuName;
                    //Session["parentRouteId"] = parentRoute.MenuId;
                    //Session["parentName"] = parentRoute.MenuName;
                    //Session["parentRoute"] = parentRoute.MenuLink;

                    //model.routeId = route.MenuId;
                    //model.routeName = name;
                    //model.reportName = route.MenuName;
                    //model.parentRouteId = parentRoute.MenuId;
                    //model.parentName = parentRoute.MenuName;
                    //model.parentRoute = parentRoute.MenuLink;

                    Session["TempProcurementReportTable"] = null;
                   // Session["excelAction"] = "ExportPriceDeskReportToExcel";
                 //  model.excelAction = "ExportPriceDeskReportToExcel";

                    //Session["pdfAction"] = "ExportProcurementReportToPdf";
                 //   model.pdfAction = "ExportProcurementReportToPdf";

                    Session["MainAction"] = "";
                    Session["Error"] = null;
                    Session["ids"] = null;
                    if (fromback != true)
                    {
                        Session["TempReportTable"] = null;
                        Session["TempReportViewTable"] = null;
                        Session["TempReportModel"] = null;
                        Session["TempFilters"] = null;

                    }

                    //if (Session["TempReportModel"] != null)
                    //{
                    //  //  model = (PriceDeskReportModel)Session["TempReportModel"];
                    //}
                    //model.Suppliers = _sfa.GetSFAs().OrderBy(x => x.SFAName).Select(s => new Suppliers { SupplierName = s.SFAName ?? "-", SupplierId = s.SFAID }).ToList();
                    //model.Suppliers.Insert(0, new Suppliers { SupplierId = 0, SupplierName = "--Select--" });


                //    return View(model);

                //}
                //else
                //{
                //    var model = (PriceDeskReportModel)Session["TempReportModel"];

                    return View(model);
                }
                return View("~/Views/Shared/ErrorPage.cshtml");
            }
            catch (Exception ex)
            {
                var routeData = this.ControllerContext.RouteData;
                LogException(ex.Message, routeData);
                if (ex.InnerException != null)
                {
                    LogException(ex.InnerException.ToString(), routeData);
                }
                return View("~/Views/Shared/ErrorPage.cshtml");
            }
        }

        public ActionResult RedirectToParent(string parentRoute, int parentRouteId)
        {
            //var parentRoute = parentRoute;//Session["parentRoute"].ToString();
            //var routeId = routeId// Session["parentRouteId"].ToString();
            Session["TempFilters"] = null;
            Session["TempReportModel"] = null;
            Session["Error"] = null;
            Session["ids"] = null;

            Response.Redirect("~/" + parentRoute + "/" + parentRouteId);
            return null;
        }

        [Route("GetReportData")]
        public ActionResult GetReportData(PriceDeskReportModel model)
        {
            try
            {
                var buttonName = Request.Form["submit"];
                if (buttonName == "Reset")
                {
                    Session["TempReportTable"] = null;
                    Session["TempReportViewTable"] = null;
                    Session["TempReportModel"] = null;
                    Session["TempFilters"] = null;
                    ViewBag.Message = null;
                    Session["Error"] = null;
                    Session["ids"] = null;
                    return RedirectToAction("PriceDeskReport", new { id = Convert.ToInt32(Session["routeId"]) });
                }

                string data = "";
                DateTime FromDate = DateTime.Now;
                DateTime ToDate = DateTime.Now;

                if (model.StartDate != null)
                {
                    FromDate = DateTime.Parse(model.StartDate).Date;
                }
                if (model.EndDate != null)
                {
                    ToDate = DateTime.Parse(model.EndDate).Date;
                }

                if (model.StartDate != null && model.EndDate != null)
                {
                    if (FromDate > ToDate)
                    {
                        ViewBag.Message = "Start date should not be greater than end date";
                    }
                }

                if (ViewBag.Message != "" && ViewBag.Message != null)
                {
                    return Json(new { data = "", msg = ViewBag.Message });
                }
                else
                {
                    var dt = pricedeskReportsPresenter.GetPriceDeskReportData(model.reportName, model);

                    if (dt != null && dt.Rows.Count > 0)
                    {
                        ViewBag.Message = null;
                        Session["TempReportTable"] = dt;
                        DataView view = new DataView(dt);
                        dt.Columns.Add("No. Of Quotes");

                        DataTable distinctValues = new DataTable();

                        if (model.reportName == "Quotes By Supplier Report")
                        {
                            distinctValues = view.ToTable(true, "Supplier", "AccountManagerName", "BusinessTypes", "No. Of Quotes");
                            distinctValues.Columns.Add("Action");

                            foreach (DataRow row in distinctValues.Rows)
                            {
                                var Quotes = (from r in dt.AsEnumerable()
                                              where r.Field<object>("Supplier").ToString() == row["Supplier"].ToString() && r.Field<object>("AccountManagerName").ToString() == row["AccountManagerName"].ToString() && r.Field<object>("BusinessTypes").ToString() == row["BusinessTypes"].ToString()
                                              let objectArray = new List<object>
                                                  {
                                                    r.Field<object>("QuoteId").ToString(),r.Field<object>("Supplier").ToString()
                                                  }

OneSourceAdmin/Views/PriceDeskReports/Details.cshtml
@model OneSourceAdminCore.Model.PriceDeskReportModel

@{
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
    ViewBag.Title = Model.reportName;
}
<style>
    .headerClass {
        background: #3b9ad2 !important;
        color: white;
        border: none !important;
    }

    .rowClass {
        border: none !important;
        border: 1px solid #ddd !important;
    }

    tr:nth-child(odd) {
        background-color: #f9f9f9;
    }

    tr:nth-child(even) {
        background-color: #fff;
    }

    .gj-grid-bootstrap tfoot tr[data-role=pager] th {
        background-color: #3b9ad2 !important;
        color: white !important;
    }
</style>

<div class="row bread-Crumb-Top" style="background-color: #216481; padding: -10px; margin-left: -20px;
                                       margin-right: -19px;">
    <div class="col-md-7" style="padding: 10px; color: #FFF;">
        @{
            <b> Reports > @Model.parentName > @Model.reportName </b>
        }
    </div>


    <div class="col-md-5" style="padding: 7px; text-align:right;">
        @if (Model.routeName == "quotesbysupplierreport")
        {
            <div style="float:right">
                @using (Html.BeginForm("PriceDeskReport", "PriceDeskReports", new { id = Model.routeId, fromBack = true }, FormMethod.Get))
                {
                    <input type="hidden" name="routeId" id="routeId" value="@Model.routeId">
                    <input type="hidden" name="routeName" id="routeName" value="@Model.routeName">
                    <input type="hidden" name="reportName" id="reportName" value="@Model.reportName">
                    <input type="hidden" name="parentRouteId" id="parentRouteId" value="@Model.parentRouteId" />
                    <input type="hidden" name="parentName" id="parentName" value="@Model.parentName" />
                    <input type="hidden" name="parentRoute" id="parentRoute" value="@Model.parentRoute" />
                    <button class="btn btn-default topAddNewButton" type="submit" id="redirectToParent" style="float:right;background-color:green">Back</button>
                }
            </div>
            using (Html.BeginForm("ExportQuotesWithDetail", "PriceDeskReports", FormMethod.Post, new { @id = "QuotesDetailToExcel" }))
            {
                <input type="hidden" name="SupplierId" id="SupplierId" value="@Model.SupplierId" />
                <input type="hidden" name="StartDate" id="StartDate" value="@Model.StartDate">
                <input type="hidden" name="EndDate" id="EndDate" value="@Model.EndDate">
                <input type="hidden" name="Quoteids" id="Quoteids" value="@Model.Quoteids" />
                <input type="hidden" name="QuoteTypeId" id="QuoteTypeId" value="@Model.QuoteTypeId" />
                <input type="hidden" name="Status" id="Status" value="@Model.Status"/>
                <input type="hidden" name="reportName" id="reportName" value="@Model.reportName"/>
                <input type="hidden" name="routeId" id="routeId" value="@Model.routeId" />
                <div style="">
                    <button class="btn btn-default topAddNewButton" type="submit" id="exportExcel" style="margin-right:10px">Export to excel</button>
                </div>
            }
        }

    </div>
</div>
<h2>Supplier Quotes</h2>
<br />
<div class="col-md-12">
    <div class="row detailGridDiv">
    </div>


</div>
<script>

    $(document).ready(function () {

        @if(Model.Quoteids!=null)
        {


            @*if (Session["Error"]!=null)
            {
                <text>
                showNotification("No line items to export.");
                </text>
            }*@


            <text>
        $(".detailGridDiv").html("");
        $(".detailGridDiv").html("<table class='scrollbar-inner' id='grid'></table>");
        StartLoader();
        var model = {QuoteIds:"@Model.Quoteids.ToString()",QuoteTypeId:"@Model.QuoteTypeId",Status:"@Model.Status"};
        $.ajax({
            url: '/SupplierQuotes',
            type: "POST",
            data: model,
            success: function (data) {
                EndLoader();
                if (data != null && data != "" && data != undefined) {

                    var table = JSON.parse(data);
                    $("#txt").val(data);
                    var tableObj = [];
                    if (table.length > 0) {

                        for (i = 0; i < Object.keys(table[0]).length; i++) {

                            var obj = {};
                            obj.field = Object.keys(table[0])[i];
                            obj.width = 100;
                            obj.sortable = true;
                            obj.align = 'left';
                            obj.headerCssClass = 'headerClass';
                            obj.cssClass = 'rowClass';

                            if(obj.field=="QuoteId"){
                                obj.title = "Quote #";
                            }
                            if(obj.field=="QuoteType"){
                                obj.title = "Quote Type";
                            }
                            if(obj.field=="AccountManagerName"){
                                obj.title = "Account Manager";
                            }
                            if(obj.field=="AccountManagerType"){
                                obj.title = "Business Type";
                            }
                            if(obj.field=="CustomerName"){
                                obj.title = "Customer";
                            }
                            @*if(@Model.Status=="Cancelled"){
                                    if(obj.field=="Status"){
                                        obj. = "Customer";
                                    }
                                }*@

                            tableObj.push(obj);
                        }

                    }

                    var detailColumns = [];
                    if(@Model.QuoteTypeId==1){
                        detailColumns = [
                   { field: 'Description', width: 200,headerCssClass:'headerClass',cssClass :'rowClass' },
                   { field: 'Manufacturer', width:100,headerCssClass:'headerClass',cssClass :'rowClass'  },
                   { field: 'Sku', width:100,headerCssClass:'headerClass',cssClass :'rowClass'   },
                   { field: 'Category', width:100,headerCssClass:'headerClass',cssClass :'rowClass'  },
                   { field: 'LeadTime', width:100,title:"Lead Time",headerCssClass:'headerClass',cssClass :'rowClass'  },
                   { field: 'EOL', width:100,headerCssClass:'headerClass',cssClass :'rowClass' },
                   { field: 'Quantity', width:100,headerCssClass:'headerClass',cssClass :'rowClass'  },
                   { field: 'UnitPrice', width:100 ,title:"Unit Price",headerCssClass:'headerClass',cssClass :'rowClass' }
                        ];
                    }
                    else if(@Model.QuoteTypeId==2){
                        detailColumns = [
                  { field: 'Description', width: 200 ,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'Manufacturer', width:100 ,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'Sku', width:100  ,headerCssClass:'headerClass',cssClass :'rowClass' },{ field: 'SerialNumber', width:100,title:'Serial #' ,headerCssClass:'headerClass',cssClass :'rowClass'  },
                  { field: 'Category', width:100,headerCssClass:'headerClass',cssClass :'rowClass'  },
                  { field: 'LeadTime', width:100,title:"Lead Time",headerCssClass:'headerClass',cssClass :'rowClass'  },
                  { field: 'EOL', width:100,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'Quantity', width:100 ,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'UnitPrice', width:100 ,title:"Unit Price",headerCssClass:'headerClass',cssClass :'rowClass' }
                        ];
                    }
                    else if(@Model.QuoteTypeId==3){
                        detailColumns = [
                  { field: 'Description', width: 200,headerCssClass:'headerClass',cssClass :'rowClass'  },
                  { field: 'Category', width:100,headerCssClass:'headerClass',cssClass :'rowClass'  },
                  { field: 'LeadTime', width:100,title:"Lead Time",headerCssClass:'headerClass',cssClass :'rowClass'  },
                  { field: 'EOL', width:100,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'Quantity', width:100 ,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'UnitPrice', width:100 ,title:"Unit Price",headerCssClass:'headerClass',cssClass :'rowClass' }
                        ];
                    }
                    else if(@Model.QuoteTypeId==4){
                        detailColumns = [
                  { field: 'ServiceType', width: 200 ,title:'Service Type',headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'SLAType', width:100,title:'SLA Type' ,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'Resources', width:100,headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'HourlyRate', width:100,title:'Hourly Rate',headerCssClass:'headerClass',cssClass :'rowClass' },
                  { field: 'TravelCharges', width:100 ,title:'Travel Charges',headerCssClass:'headerClass',cssClass :'rowClass' },
                        ];
                    }


                    if (table.length > 50) {
                        var grid = $('#grid').grid({
                            primaryKey: 'QuoteId',
                            dataSource: table,
                            columns: tableObj,
                            pager: { limit: 50, sizes: [50, 100, 500, 1000] },
                            cache: false,
                            uiLibrary: 'bootstrap',
                            detailTemplate: '<div><table/></div>'
                        });
                        grid.on('detailExpand', function (e, $detailWrapper, id) {
                            $detailWrapper.find('table').grid({
                                params: { Quoteids: id, QuoteTypeId: "@Model.QuoteTypeId" },
                                dataSource: '/PriceDeskReports/GetQuoteResponseItems',
                                columns:detailColumns,
                                pager: { limit: 5, sizes: [10, 50, 100, 500, 1000] },
                                cache: false,
                                headerCssClass:'headerClass',
                                cssClass : 'rowClass',
                                uiLibrary: 'bootstrap'
                            });
                        });
                        grid.on('detailCollapse', function (e, $detailWrapper, id) {
                            $detailWrapper.find('table').grid('destroy', true, true);
                        });
                    }
                    else {
                        var grid = $('#grid').grid({
                            primaryKey: 'QuoteId',
                            dataSource: table,
                            columns: tableObj,
                            pager: null,
                            cache: false,
                            uiLibrary: 'bootstrap',
                            detailTemplate: '<div><table/></div>'
                        });
                        grid.on('detailExpand', function (e, $detailWrapper, id) {
                            $detailWrapper.find('table').grid({
                                params: { Quoteids: id, QuoteTypeId: "@Model.QuoteTypeId" },
                                dataSource: '/PriceDeskReports/GetQuoteResponseItems',
                                columns:detailColumns,
                                pager: { limit: 5, sizes: [10, 50, 100, 500, 1000] },
                                cache: false,
                                headerCssClass:'headerClass',
                                cssClass : 'rowClass',
                                uiLibrary: 'bootstrap'
                            });
                        });
                        grid.on('detailCollapse', function (e, $detailWrapper, id) {
                            $detailWrapper.find('table').grid('destroy', true, true);
                        });
                    }
                    var refreshButton = $("button[data-role='page-refresh']");
                    if (refreshButton != undefined)
                    {
                        refreshButton.hide();
                    }
                    var selectCounter = $("select[data-role='page-size']")[0];
                    if (selectCounter != undefined) {
                        selectCounter.style.width = "80px";
                    }

                    //$(".gj-grid-wrapper").floatingScroll();
                    $(".gj-grid-wrapper").attr("style","overflow:auto");

                }
                else {
                    showNotification("Something went wrong, please try again later!");
                }
            }
        });
        </text>

        }


    });


</script>

OneSourceAdmin/Views/PriceDeskReports/_ReportGrids.cshtml
@model OneSourceAdminCore.Model.PriceDeskReportModel
@using OneSourceAdminCore.Model
@using GridMvc.Html

<br />
<div class="col-md-12">
    <div class="row gridDiv">
    </div>


</div>