OneSourceAdmin/Controllers/CountryController.cs
using System.Web.Mvc;
using OneSourceAdminCore.Presenter;
using System;
using System.Collections.Generic;
using System.Linq;
using OneSourceAdminCore.Entity;
using OneSourceAdminCore.Helper;
using OneSourceAdminCore.Model;

namespace OneSourceAdmin.Controllers
{
    /// <summary>   
    /// Date created : Feb 04 2016
    /// Created by : Muhammad Wasim (BSCE,MS-CSIT)
    /// This Controller Class is responsible for Adding, Editing, Listing of Country Alert"
    /// </summary>

    public class CountryController : BaseController
    {
        ///<summary>
        /// This Action is responsible For providing View Of Country Alert (Alert>>Country)
        /// </summary>
        /// <returns> 
        /// Return Error View in case of Exception
        /// Return to Login Action of Account Controller in case of session timeout
        /// Return Index View if all Working Well
        /// </returns>




        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    CountryPresenter cp = new CountryPresenter();
                    CustomerPresenter custp = new CustomerPresenter();
                    CountryModel model = new CountryModel
                    {
                        Countries = cp.GetCountries(),
                        CountryAlerts = cp.GetCountryAlert(),
                        Customers = custp.GetCustomers()

                    };

                    @ViewBag.AddEditAccess = isAddEditAllow("CountryAlert");

                    ViewBag.Message = TempData["Message"];
                    return View(model);
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        /// <summary>
        /// This Action is responsible For Adding and Editing of Country Alert
        /// </summary>
        /// <returns> 
        /// Return Error View in case of Exception
        /// Return to Login Action of Account Controller in case of session timeout
        /// Return Index View if all Working Well
        /// </returns>
        [HttpPost]
        public ActionResult AddCountryAlert(tblCountryAlert model)
        {
            if (Session["UserID"] != null)
            {
                try
                {

                    if (!ValidateFields(model)) return RedirectToAction("Index");

                    CountryPresenter cp = new CountryPresenter();
                    int count;
                    //For Edit
                    if (model.CountryAlertId != 0)
                    {
                        count = cp.EditCountryAlert(model, Convert.ToInt32(Session["UserID"]));
                        if (count > 0) TempData["Message"] = "Alert has been edited";
                        return RedirectToAction("Index");
                    }
                    //

                    count = cp.AddCountryAlert(model, Convert.ToInt32(Session["UserID"]));
                    if (count > 0) TempData["Message"] = "Alert has been added";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        /// <summary>
        /// This Action is responsible For Deleting selected country 
        /// </summary>
        /// <returns> 
        /// Return Error View in case of Exception
        /// Return to Login Action of Account Controller in case of session timeout
        /// Return Index View if all Working Well
        /// </returns>
        public ActionResult DeleteAlert(string id)
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    int countryId;
                    if (!int.TryParse(id, out countryId))
                    {
                        return View("~/Views/Shared/ErrorPage.cshtml");
                    }
                    CountryPresenter cp = new CountryPresenter();
                    int count = cp.DeleteCountryAlert(countryId);
                    if (count > 0) TempData["Message"] = "Alert has been deleted";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

        }

        /// <summary>
        /// This Action is responsible For Validating Data which has been post to AddCountryAlert Action
        /// </summary>
        /// <returns> 
        /// Return boolean result
        /// </returns>
        public bool ValidateFields(tblCountryAlert model)
        {
            if (model.CountryId == 0)
            {
                TempData["Message"] = "Please Provide Country";
                return false;
            }
            if (Convert.ToDateTime(model.StartDate).Date.Year == 1)
            {
                TempData["Message"] = "Please Provide Start Date";
                return false;
            }
            if (Convert.ToDateTime(model.EndDate).Date.Year > 1)
            {
                if (model.StartDate.Date > Convert.ToDateTime(model.EndDate).Date)
                {
                    TempData["Message"] = "Start Date must be less than End Date";
                    return false;
                }
            }
            if (string.IsNullOrEmpty(model.Alert))
            {
                TempData["Message"] = "Please Provide Alert";
                return false;
            }

            return true;
        }


        #region  Country CRUD Operations
        //12-28-2016 by Danyal Manzoor
        /// <summary>
        /// Show the list of countries
        /// </summary>
        /// <returns>View</returns>
        //[Route("locale-settings/country/{countryName?}")]
        public ActionResult CountryListing(string countryName = "")
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    var countryService = new CountryPresenter();
                    var modal = new CountryCrudModal();
                    var chkAddAccess = (List<UserAccessCheckModel>)Session["UserAuthTokens"];
                    if (chkAddAccess.Any(x => x.DataToken == "localeCountries" && x.AddEditAccess))
                    {
                        @ViewBag.AddEditAccess = true;
                    }
                    modal.CountryListing = countryService.GetCountriesListing(countryName);
                    modal.DateFormatsList = countryService.GetDateFormatesList();
                    modal.TimeZonesList = countryService.GetTimeZonesList();
                    modal.IsoCountriesList = countryService.GetIsoCountryListToAdd();

                    return View(modal);
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return View("~/Views/Shared/ErrorPage.cshtml");
                }

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

        }

        public JsonResult UpdateCountryStatus(int countryId, bool isActive)
        {
            if (Session["UserID"] != null)
            {
                try
                {
                    var countryService = new CountryPresenter();
                    var userId = Convert.ToInt32(Session["UserID"]);
                    var data = countryService.UpdateCountryStatus(countryId, isActive, userId);
                    return Json(data, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    var routeData = this.ControllerContext.RouteData;
                    LogException(ex.Message, routeData);
                    if (ex.InnerException != null)
                    {
                        LogException(ex.InnerException.ToString(), routeData);
                    }
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json("sessionOut", JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetCountryById(int countryId)
        {
            if (Session["UserID"] != null)
            {
                try
                {

OneSourceAdmin/Views/Country/Index.cshtml
@model OneSourceAdminCore.Model.CountryModel
@{
    ViewBag.Title = "Country Alerts";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<style>
    .input-medium {
        width: 270px !important;
    }
</style>
<div class="clearfix"></div>
<div class="row bread-Crumb-Top" style="background-color:#216481; padding: -10px; margin-left: -20px;
                                       margin-right: -19px;">
    <div class="col-md-3" style="padding:10px; color:#FFF;"><b> Alert > Country </b></div>
    <div class="col-md-3" style="padding:10px;"></div>
    <div class="col-md-3" style="padding:10px;"></div>
</div>
<div style="text-align: center; color: blue; font-weight: 600; margin-top: 10px; margin-bottom: -20px;">
    @if (ViewBag.Message != null)
    {
        @*<span>@ViewBag.Message</span>*@
        <div class="alert alert-info fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <span>@ViewBag.Message</span>
        </div>
    }
</div>
 @if (ViewBag.AddEditAccess == true)
              {

using (Html.BeginForm("AddCountryAlert", "Country", FormMethod.Post, new { @id = "CountryForm" }))
{
    @*<div class="row" style="background-color: #3a9ada; padding: -10px; margin-left: -20px; margin-top: 30px; margin-right: -19px;">
           <div class="col-md-4">
                <h1 style="color: #fff;">Country</h1>
            </div>
            <div class="col-md-4" style="font-size: 32px; color: #FFF; padding: 18px; padding-top: 2px;">
            </div>
            <div class="col-md-4"></div>
        </div>*@
    <div class="row" style="margin-top: 60px;">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="form-group">
                <label class="control-label col-md-3"><span style="color:red">* </span>Country </label>
                <div class="col-md-7">
                    <input type="hidden" name="CountryName" id="CountryName">
                    <input type="hidden" name="CountryAlertId" id="CountryAlertId">
                    @Html.DropDownList("CountryId", new SelectList(Model.Countries,
                        "Key", "Value"), "--Select--",
  new { @id = "CountryID", @valueFor = "CountryName", @class = "form-control ", @tabindex = "-1" })
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top: 15px;">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="form-group">
                <label class="control-label col-md-3"><span style="color:red">&nbsp;&nbsp; </span>Customer </label>
                <div class="col-md-7">
                    <input type="hidden" name="CustomerName" id="CustomerName">
                    @Html.DropDownList("CustomerId", new SelectList(Model.Customers,
                        "Key", "Value"), "All",
  new { @id = "CustomerID", @valueFor = "CustomerName", @class = "form-control ", @tabindex = "-1" })
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top: 15px;">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="form-group">
                <label class="control-label col-md-3"><span style="color:red">* </span>Start Date</label>
                <div class="col-md-5">
                    <div class="input-group input-medium date date-picker" data-date="@DateTime.Now.Date" data-date-format="mm/dd/yyyy" data-date-viewmode="years">
                        <input type="text" name="StartDate" value="@DateTime.Now.Date.Date.ToString("MM/dd/yyyy")" class="form-control" readonly>
                        <span class="input-group-btn">
                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                        </span>
                    </div>
                </div>
                <div class="col-md-1">
                    <button class="resetDate" type="button" style="width: 44px; border-style: none; background-color: white; height: 34px;">
                        <img src="/Content/images/reset-btn.png">
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="margin-top: 15px;">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="form-group">
                <label class="control-label col-md-3"><span style="color: red; padding-left: 11px;"> </span>End Date</label>
                <div class="col-md-5">
                    <div class="input-group input-medium date date-picker endDate" data-date="@DateTime.Now.Date" data-date-format="mm/dd/yyyy" data-date-viewmode="years">
                        <input type="text" name="EndDate" value="@DateTime.Now.Date.Date.ToString("MM/dd/yyyy")" class="form-control" readonly>
                        <span class="input-group-btn">
                            <button class="btn default" type="button"><i class="fa fa-calendar"></i></button>
                        </span>
                    </div>
                </div>
                <div class="col-md-1">
                    <button class="resetDate" type="button" style="width: 44px; border-style: none; background-color: white; height: 34px;">
                        <img src="/Content/images/reset-btn.png">
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="margin-top: 15px;">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="form-group">
                <label class="control-label col-md-3"><span style="color:red">* </span>Alert</label>
                <div class="col-md-7" style=" height: 100px !important;">
                    <textarea rows="4" name="Alert" class="form-control" cols="45"></textarea>
                    @*<button type="submit" class="btn btn-default btnSubmit" style="float: left; margin-left: 20px; margin: 0px;" id="per">Submit</button>
                        <button type="button" class="btn btn-default btnReset" style="float: left; margin-left: 5px;" id="per">Reset</button>*@
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top: 15px;">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <label class="control-label col-md-3"><span style="color: red; padding-left: 11px;"> </span>Top Story</label>
            <div class="col-md-7">
                <div class="">
                    <input type="hidden" name="IsTopStory" id="IsTopStory">
                    <input type="checkbox" id="chkTopStory">
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top: 15px;">
        <div class="col-md-4"></div>
        <div class="col-md-7" style=" padding-left: 23px;">
            <button type="submit" class="btn btn-default btnSubmit" style="float: left; margin-left: 20px; margin: 0px;" id="per">Submit</button>
            <button type="button" class="btn btn-default btnReset" style="float: left; margin-left: 5px;" id="per">Reset</button>
        </div>
        <br>
        <br>
    </div>

}}
<br>
<br>
<div class="row">
    <div class="col-md-12">
        @using GridMvc.Html;
        @if (Model.CountryAlerts != null && Model.CountryAlerts.Count > 0)
        {
            @Html.Grid(Model.CountryAlerts).Columns(columns =>
              {
                  columns.Add(C => C.CountryName).Sortable(true).Filterable(true).Titled("Country").Encoded(false).Sanitized(false).SetWidth(5)
        .RenderValueAs(o => @<span><input type="hidden" value="@o.CountryAlertId"><input type="hidden" value="@o.CountryId"><input type="hidden" value="@o.IsTopStory.ToString()"><input type="hidden" value="@o.CustomerId.ToString()">@o.CountryName</span>);
                  columns.Add(c => c.CustomerName).Sortable(true).Filterable(true).Encoded(false).Sanitized(false).Titled("Customer").SetWidth(30)
           .RenderValueAs(x => @<span>@(!string.IsNullOrEmpty(x.CustomerName) == true ? x.CustomerName : "All")</span>);

                  columns.Add(c => c.strStartDate).Sortable(true).Filterable(true).Titled("Start Date").SetWidth(30);
                  columns.Add(c => c.strEndDate).Sortable(true).Filterable(true).Titled("End Date").SetWidth(30);

                  columns.Add().Encoded(false).Sanitized(false).Sortable(false).Filterable(false).Titled("Alert").
                      SetWidth(30).RenderValueAs(x => @<span fullval="@x.Alert">@(x.Alert.Length > 50 ? x.Alert.Substring(0, 50) + "..." : x.Alert)</span>);

              if (ViewBag.AddEditAccess == true)
              {

                  columns.Add().Encoded(false).Sanitized(false).Sortable(false).Filterable(false).SetWidth(30).
                       RenderValueAs(o => @<a style="color:blue" onclick="EditAlert(this)">Edit </a>);

                  columns.Add().Encoded(false).Sanitized(false).Sortable(false).Filterable(false).SetWidth(30).
                       RenderValueAs(o => @<a style="color:blue" onclick="DeleteAlert(this)">Delete </a>);

                  }
              }).WithPaging(15)
        }
    </div>
</div>
<script>

    $(document).ready(function () {
        StartLoader();
        var dateToday = new Date();
        $('.date-picker').datepicker({
            todayHighlight: true,
            startDate: dateToday,
            autoclose: true
        });
        setTimeout(function () {
            $('.alert-info').slideUp();
        }, 2000);
    });
    $(window).load(function () {
        EndLoader();

        $("a:contains('Customer Country Budget')").parent().removeClass('active');
    });
    function EditAlert(event) {
        var id = $($(event).parent().parent().find('input:hidden')[0]).val();
        $('#CountryAlertId').val(id);
        id = $($(event).parent().parent().find('input:hidden')[1]).val();
        $('#CountryID').val(id);
        $('#CountryName').val($(event).parent().parent().find("td[data-name='CountryName']").find('span').text());
        var date = $(event).parent().parent().find("td[data-name='strStartDate']").text();
        $("input[name='StartDate']").val(date);
        date = $(event).parent().parent().find("td[data-name='strEndDate']").text();
        $("input[name='EndDate']").val(date);
        $("textarea[name='Alert']").val($(event).parent().parent().find("td[data-name='strEndDate']").next().find('span').attr('fullval'));
        $('body').animate({ scrollTop: 0 }, 'slow');

        $('#CountryID').attr('disabled', 'disabled');

        var isTopStory = $($(event).parent().parent().find('input:hidden')[2]).val();
        if (isTopStory === "True") {
            $('#chkTopStory').prop("checked", true);
            $('#IsTopStory').val('True');
        } else {
            $('#chkTopStory').prop("checked", false);
            $('#IsTopStory').val('False');
        }

        var id = $($(event).parent().parent().find('input:hidden')[3]).val();
        $('#CustomerID').val(id == 0 ? '' : id);
        $('#CustomerName').val(id == 0 ? '' : $('#CustomerID option:selected').text());
    }


    function DeleteAlert(event) {

        if (confirm("Are you sure you want to delete this record?")) {
            StartLoader();
            var currentCountryId = $(event).parent().parent().find('input:hidden').val();
            window.location.href = '/Country/DeleteAlert?id=' + currentCountryId;
        }
    }

    //For Country
    $("#CountryID").change(function () {
        $('#CountryAlertId').val('0');
    });

    $('#CountryForm').submit(function () {
        if ($("#CountryID").val() === '') {
            alert('Please provide country');
            return false;
        }
        if ($("input[name='StartDate']:text").val().trim() === '') {
            alert("Please provide start date");
            return false;
        }
        if ($("input[name='EndDate']:text").val().trim() !== '') {
            if (new Date($("input[name='StartDate']:text").val()) > new Date($("input[name='EndDate']:text").val())) {
                alert("Please provide start date less than end date");
                return false;
            }
        }

        if ($("textarea[name='Alert']").val().trim() === '') {
            alert('Please provide alert');
            return false;
        }
        $('#CountryID').removeAttr('disabled');
        $('#CustomerName').val($('#CustomerID').val() == '' ? '' : $('#CustomerID option:selected').text());
        StartLoader();
    });

    $('.btnReset').click(function () {
        $('#CountryAlertId').val('0');
        $('#CountryID').val('');
        $("input[name='StartDate']").val('');
        $("input[name='EndDate']").val('');
        $("textarea[name='Alert']").val('');
        $('#CountryID').removeAttr('disabled');
        $('#chkTopStory').prop("checked", false);
        $('#CustomerID').val("");
        $('#CustomerName').val("");
    });

    $('.date-picker').click(function () {
        if ($(this).find('input').val().trim() !== '') {
            $(this).datepicker("setDate", new Date($(this).find('input').val()));
        }
    });
    $('.resetDate').click(function () {
        $(this).parent().parent().find('.date-picker').datepicker("setDate", "+0");
        $(this).parent().siblings().find('input').val("");
    });
    $('#chkTopStory').click(function () {
        $('#IsTopStory').val($(this).prop('checked'));
    });
    $(document).ready(function () {
        $(".page-sidebar-menu").find(".alert").addClass("open");
        $(".page-sidebar-menu .alert").find(".sub-menu").css("display", "block");
        $(".page-sidebar-menu .alert").find(".countryalert").addClass("active");
    });
</script>

OneSourceAdmin/Views/Country/_CountryCrudPartial.cshtml
@model OneSourceAdminCore.Model.CountryCrudModal

<div class="addEditDiv" style="margin-top: 60px; display: none;">
    <input type="hidden" id="crudMsg" value="@(TempData["crudMsg"] != null ? TempData["crudMsg"].ToString() : "")"/>
    <input type="hidden" id="crudUpdate" value="@(TempData["crudEditMsg"] != null ? TempData["crudEditMsg"].ToString() : "")" />
    @using (Html.BeginForm("AddEditCountry", "Country", FormMethod.Post, new { @id = "countryForm" }))
    {
        <input type="hidden" name="CountryID" value="0" id="CountryID" />
        <div class="row" style="margin-top: 15px" id="isoCountryDiv">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-4"><span style="color: red">* </span>ISO Country : </label>
                    <div class="col-md-7 isoDrpDiv">
                        <input type="hidden" name="CountryCodeID" value="@Model.IsoCountriesList.FirstOrDefault().Key" id="CountryCodeID"/>
                        @Html.DropDownList("CurrencyCodeID", new SelectList(Model.IsoCountriesList,
                            "Key", "Value"),
                            new {@id = "CountryCodeDrp", @valueFor = "CountryName", @idFor = "CountryCodeID", @class = "form-control ", @tabindex = "-1"})
                    </div>
                    <div class="col-md-7 isoLblDiv" style="display: none">
                        <label style="padding-left: 0px;" class="control-label col-md-5">-</label>
                    </div>
                </div>

            </div>
        </div>
        <div class="row" style="margin-top: 15px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-4"><span style="color: red">* </span>Country Name :</label>
                    <div class="col-md-7">
                        <input type="text" value="@Model.IsoCountriesList.FirstOrDefault().Value" name="CountryName" data-defaultVal="" maxlength="50" id="CountryName" readonly="readonly" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 15px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-4"><span style="color: red">* </span>Date Format :</label>
                    <div class="col-md-7">

                        <input type="hidden" name="DefaultDateFormatID" id="DefaultDateFormatID" value="@Model.DateFormatsList.FirstOrDefault().Key">
                        @Html.DropDownList("CurrencyCodeID", new SelectList(Model.DateFormatsList,
                            "Key", "Value"),
                            new { @id = "dateFormatDrp", @idFor = "DefaultDateFormatID", @class = "form-control " })
                    </div>
                </div>

            </div>
        </div>
        <div class="row" style="margin-top: 15px;">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-4"><span style="color: red">* </span>Time Zone :</label>
                    <div class="col-md-7">

                        <input type="hidden" name="DefaultTimeZoneID" id="DefaultTimeZoneID" value="@Model.TimeZonesList.FirstOrDefault().Key">
                        @Html.DropDownList("CurrencyCodeID", new SelectList(Model.TimeZonesList,
                            "Key", "Value"),
                            new { @id = "timeZoneDrp", @idFor = "DefaultTimeZoneID", @class = "form-control " })
                    </div>
                </div>

            </div>
        </div>
        <div class="row" style="margin-top: 15px; display: none" id="workShiftDiv">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <label class="control-label col-md-4"><span style="color: red; padding-left: 11px;"> </span>Work Shifts :</label>
                <div class="col-md-7">

                    <a style="color: blue" id="WorkShiftsPopupLink">Add/Modify Work Shifts</a>

                </div>

            </div>
        </div>
        <div class="row" style="margin-top: 15px; display: none" id="isActiveDiv">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <label class="control-label col-md-4"><span style="color: red; padding-left: 11px;"> </span>Is Active</label>
                <div class="col-md-7">

                    <input type="hidden" name="IsActive" id="IsActive">
                    <input class="isActiveCrudButton" checkboxfor="IsActive" checked data-toggle="toggle" data-onstyle="success" data-offstyle="warning" data-on="Yes" data-size="small" data-off="No" type="checkbox">

                </div>

            </div>
        </div>

        <div class="row" style="margin-top: 15px; display: none" id="lastUpdatedDiv">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <label class="control-label col-md-4"><span style="color: red; padding-left: 11px;"> </span>Last Updated(mm/dd/yyyy) :</label>
                <div class="col-md-7">
                    <label style="padding-left: 0px;" class="control-label col-md-5 updatedDate">-</label>
                </div>

            </div>
        </div>
        <div class="row" style="margin-top: 15px; display: none" id="lastUpdatedByDiv">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label col-md-4"><span style="color: red; padding-left: 11px;"> </span>Last Updated By</label>
                    <div class="col-md-7">
                        <label style="padding-left: 0px;" class="control-label col-md-5 updatedBy">-</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 15px;">

            <div class="col-md-2"></div>
            <div class="col-md-8" style="">
                <div class="form-group">
                    <div class="col-md-4"></div>
                    <div class="col-md-7" style="text-align: right;">
                        <button type="submit" class="btn btn-default btnSubmit" style="margin: 0px;" id="per">Submit</button>
                        <button type="button" class="btn btn-default btnReset" style="" id="per">Reset</button>
                    </div>
                </div>
            </div>
            <br>
            <br>
        </div>
    }
</div>